/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://c4mjjnx4f5ajvb4w5aub7drlem.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-leaghdaox5gtzhlealn5qw3qeq",
    "aws_cloud_logic_custom": [],
    "aws_cognito_identity_pool_id": "us-east-1:d92ea7d7-e51f-4bf4-91ef-a634c1830983",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rbVssvKAn",
    "aws_user_pools_web_client_id": "4o76f8u6osueuom19cih77rlf9",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
